version: '3.8'

services:
  # Flask 웹 애플리케이션
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-super-secret-key-change-this-in-production
      - DATABASE_URL=sqlite:///data/typing_practice.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - typing-network

  # Nginx 리버스 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - typing-network

  # PostgreSQL 데이터베이스 (선택사항 - 더 큰 규모의 서비스용)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: typing_practice
  #     POSTGRES_USER: typing_user
  #     POSTGRES_PASSWORD: typing_password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped
  #   networks:
  #     - typing-network

  # Redis 캐시 (선택사항 - 세션 관리용)
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped
  #   networks:
  #     - typing-network

networks:
  typing-network:
    driver: bridge

volumes:
  postgres_data:
